---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-conf-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-device",
      "device": "ens192",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.200.1/24",
        "rangeStart": "192.168.200.1",
        "rangeEnd": "192.168.200.1"
      }
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-conf-2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-device",
      "device": "ens224",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.300.1/24",
        "rangeStart": "192.168.300.1",
        "rangeEnd": "192.168.300.1"
      }
    }'

---
apiVersion: v1
kind: Pod
metadata:
  name: dut
  annotations:
    k8s.v1.cni.cncf.io/networks: "sriov-conf-1,sriov-conf-2"
spec:
  containers:
  - name: dut
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
