apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-operator
  template:
    metadata:
      labels:
        name: node-operator
    spec:
      serviceAccountName: node-operator
      containers:
        - name: node-operator
          # Replace this with the built image name
          image: elynn/node-operator:v.0.0.1
          command:
          - node-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "node-operator"
