# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.hostname = 'devstack'

  #config.vm.box = "ubuntu/trusty64"
  config.vm.box = "boxcutter/ubuntu1404"
  #config.vm.box = "puppetlabs/centos-7.0-64-nocm"
  #config.vm.box = "bento/centos-7.1"
  #config.vm.box = "boxcutter/centos71"
  #config.vm.box = "puppetlabs/centos-6.6-64-nocm"

  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder "./stack", "/opt/stack"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "8192"
  #   vb.cpu = "2"
    vb.customize ['modifyvm', :id, '--memory', '6093']
    vb.customize ['modifyvm', :id, '--cpus',   '2']
    unless File.exist?('stack-volumes-default.vdi')
      vb.customize ["createhd",  "--filename", "stack-volumes-default", "--size", 10240]
    end
    if config.vm.box == 'ubuntu/trusty64' then
      controller_name = 'SATAController'
    else
      controller_name = 'SATA Controller'
    end
    vb.customize ["storageattach", :id, "--storagectl", controller_name, "--port", "1", "--type", "hdd", "--medium", "stack-volumes-default.vdi"]
    unless File.exist?('stack-volumes-lvmdriver-1.vdi')
      vb.customize ["createhd",  "--filename", "stack-volumes-lvmdriver-1", "--size", "10240"]
    end
    vb.customize ["storageattach", :id, "--storagectl", controller_name, "--port", "2", "--type", "hdd", "--medium", "stack-volumes-lvmdriver-1.vdi"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision :shell do |shell|
    shell.path = 'run_devstack.sh'
    shell.privileged = false
  end
end
